name: Node CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install
        run: make install
        env:
          CI: true
      - name: Run linter
        run: make lint
      - name: Run build
        run: make build-ci
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          SESSION_KEY: ${{ secrets.SESSION_KEY }}
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
